### PR TITLE
Renew Demo

### PR DESCRIPTION
**Pull request by graphemecluster**
Pull Request opened according to #407.
This demo provide a simple interface for choosing or uploading images and videos for processing.

### CODE REVIEW

**Comment by AliaksandrSiarohin** [comment]
Please make a separate file simplified_demo.py.

**Comment by graphemecluster** [comment]
Why? I really don't think using Google Drive is a good option.

**Comment by AliaksandrSiarohin** [comment]
There is no visualizations and explanations troughout.

**Comment by graphemecluster** [comment]
What explanations are required?
I can't see a meaningful explanation in your demo.

**Comment by graphemecluster** [comment]
I think compromising by adding back your demo as old_demo.ipynb would be a good idea. What do you think?

**Comment by AliaksandrSiarohin** [comment]
Ok, seems reasonable. I cant see a colab button when I open your notebook in your repository. Did you commit it trough colab?

**Comment by graphemecluster** [comment]
Since the Colab button is still missing even if I committed it through Google Colab, I manually added the button. This time the button should appear.

**Comment by AliaksandrSiarohin** [comment]
Ok. Thank you for your contribution.

**Comment by AliaksandrSiarohin** [comment]
Can you investigate issue #424 please?

**Comment by graphemecluster** [comment]
It should work but as the questioner said there may be a file size limit. A simple workaround would be dropping the video to the `demo/videos` folder in the sidebar with the name `5.mp4` (after cloning) and changing `range(5)` to `range(6)` in the Python code.

And I recommend you to place the Open in Colab button directly in README like [this link](https://colab.research.google.com/github/AliaksandrSiarohin/first-order-model/blob/master/demo.ipynb)
`[this link](https://colab.research.google.com/github/AliaksandrSiarohin/first-order-model/blob/master/demo.ipynb)`

**Pull request merged**
