### PR TITLE
Update demo.py; load() is broken

### PR DESCRIPTION
**Pull request by marcasty**

### CODE REVIEW

**Comment by chacorp** [comment]
for the Colab demo, reinstall pyyaml with `!pip install pyyaml==5.4.1`
this will fix the error below
```
TypeError: load() missing 1 required positional argument: 'Loader' in Google Colab
```

**Comment by Zoout** [comment]
> for the Colab demo, reinstall pyyaml with `!pip install pyyaml==5.4.1` this will fix the error below
> 
> ```
> TypeError: load() missing 1 required positional argument: 'Loader' in Google Colab
> ```

solved the problem,thank you!

**Comment by graphemecluster** [comment]
Hello, I am the author of `demo.ipynb`.
Don't forget to modify `requirements.txt`:
```diff
- PyYAML==5.1
+ pyyaml==6.0
```

**Comment by graphemecluster** [comment]
Hello, I am the author of `demo.ipynb`.
Don't forget to modify `requirements.txt`:
```diff
- PyYAML==5.1
+ PyYAML==6.0
```

**Pull request merged**
