### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by mikaelhg**
You already have a pretty good `requirements.txt` and this will further simplify future compatibility.

### CODE REVIEW

**Comment by AliaksandrSiarohin** [comment]
Thank docker will be indeed helpfull for the others.  Can you please provide a description in README.md on how to run and what you need (e.g os requirements, nvidia-docker...).

**Comment by wisehackermonkey** [comment]
## @mikaelhg 
#### I'm trying to build a docker container to use with [openfaas](openfaas.com).

#### _have you published your docker container?_

**Comment by mikaelhg** [comment]
I have not, as the weird repo license would require me to look into what redistribution would mean.

**Comment by mikaelhg** [comment]
@AliaksandrSiarohin: here's some documentation, please let me know if you'd like more of it.

**Comment by Jakousa** [comment]
Great job. I ran this successfully on mac as well with --cpu.

**Comment by AliaksandrSiarohin** [comment]
> @AliaksandrSiarohin: here's some documentation, please let me know if you'd like more of it.

Everything seems ok, was trying to install and check. Thank you for your help.

**Pull request merged**
